import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const statusText = {
    not_installed: "未安装",
    downloading: "下载中",
    paused: "已暂停",
    installed: "已安装",
    failed: "下载失败"
};
export const ModelRow = ({ model, onDownload, onPause, onResume, onCancel, onDelete }) => (_jsxs("div", { className: "grid grid-cols-[1.2fr_120px_120px_170px] items-center gap-2 rounded-xl border border-borderSoft bg-white px-3 py-3 text-sm", children: [_jsxs("div", { children: [_jsx("div", { className: "font-medium", children: model.language ?? "中文语音识别" }), _jsx("div", { className: "text-xs text-textMuted", children: model.version })] }), _jsx("div", { className: "text-textMuted", children: statusText[model.status] }), _jsxs("div", { className: "text-textMuted", children: [model.size.toFixed(1), " GB"] }), _jsxs("div", { className: "flex items-center justify-end gap-1", children: [model.status === "not_installed" && (_jsx("button", { className: "btn-ghost text-xs", onClick: () => onDownload(model.id), children: "\u4E0B\u8F7D" })), model.status === "downloading" && (_jsxs(_Fragment, { children: [_jsx("button", { className: "btn-ghost text-xs", onClick: () => onPause(model.id), children: "\u6682\u505C" }), _jsx("button", { className: "btn-ghost text-xs", onClick: () => onCancel(model.id), children: "\u53D6\u6D88" })] })), model.status === "paused" && (_jsx("button", { className: "btn-ghost text-xs", onClick: () => onResume(model.id), children: "\u7EE7\u7EED" })), model.status === "failed" && (_jsx("button", { className: "btn-ghost text-xs", onClick: () => onDownload(model.id), children: "\u91CD\u8BD5" })), model.status === "installed" && (_jsx("button", { className: "btn-ghost text-xs text-red-500", onClick: () => onDelete(model.id), children: "\u5220\u9664" }))] }), (model.status === "downloading" || model.status === "failed") && (_jsx("div", { className: "col-span-4 mt-1 h-1.5 rounded-full bg-slate-100", children: _jsx("div", { className: "h-full rounded-full bg-accent", style: { width: `${model.progress ?? 0}%` } }) }))] }));
